#!/usr/bin/env python3
"""Render the JSON output of extract-tb-spells.py as a TS module."""
import json
import sys


HEADER = """// mvtt, an RPG virtual tabletop
// Copyright (C) 2026, Adam Jacob
//
// This file is part of mvtt.
//
// mvtt is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation.
//
// mvtt is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with mvtt.  If not, see <https://www.gnu.org/licenses/>.

// AUTO-GENERATED by scripts/extract-tb-spells.py | scripts/spells-json-to-ts.py
// Source: data/rules-corpus-permanent/{dh,lmm} (extracted from the
// canonical TB2 PDFs in reference/).
//
// Edits made here are preserved across re-seed via the catalog merge
// engine's override-tracking. The page reference is the source of
// truth for casting prose; data needed to play the spell (name,
// circle, school, casting kind/Ob/time, materials, focus, scribe/
// learn obstacles) lives inline.

import type { TbSpellTemplate } from "./spell-catalog-types.js";

export const TB_SPELL_TEMPLATES: ReadonlyArray<TbSpellTemplate> = [
"""


def js_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    data = json.load(open(sys.argv[1] if len(sys.argv) > 1 else "/tmp/spells.json"))
    print(HEADER, end="")
    for s in data:
        c = s["casting"]
        fixed = "null" if c["fixedOb"] is None else str(c["fixedOb"])
        versus = "null" if c["versusSkill"] is None else js_string(c["versusSkill"])
        print(f"  {{")
        print(f"    id: {js_string(s['id'])},")
        print(f"    name: {js_string(s['name'])},")
        print(f"    circle: {s['circle']},")
        print(f"    school: {js_string(s['school'])},")
        print(f"    sourceBook: {js_string(s['sourceBook'])},")
        print(f"    sourcePage: {s['sourcePage']},")
        print(f"    casting: {{")
        print(f"      kind: {js_string(c['kind'])},")
        print(f"      fixedOb: {fixed},")
        print(f"      versusSkill: {versus},")
        print(f"      castingTime: {js_string(c['castingTime'])},")
        print(f"      duration: {js_string(c['duration'])},")
        print(f"      materials: {js_string(c['materials'])},")
        print(f"      focus: {js_string(c['focus'])},")
        print(f"    }},")
        print(
            f"    learning: {{ scribeOb: {s['learning']['scribeOb']}, "
            f"learnOb: {s['learning']['learnOb']} }},"
        )
        print(f"  }},")
    print("];")


if __name__ == "__main__":
    main()
