// mvtt, an RPG virtual tabletop
// Copyright (C) 2026, Adam Jacob
//
// This file is part of mvtt.
//
// mvtt is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation.
//
// mvtt is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with mvtt.  If not, see <https://www.gnu.org/licenses/>.

import { definePlugin, qualifiedName } from "@vtt/substrate";
import {
  CharacterListExclusionSlot,
  CharacterSheetActionsSlot,
  CharacterSheetIdentitySlot,
  CharacterSheetTabsSlot,
  CharacterSheetVitalsSlot,
  type CharacterListExclusion,
} from "@vtt/characters/shared";
import { LinkKindsSlot } from "@vtt/notes/shared";
import { BlockKindsSlot } from "@vtt/adventures/shared";
import {
  characterBlockKind,
  encounterBlockKind,
  itemBlockKind,
  lootBlockKind,
  monsterBlockKind,
  npcBlockKind,
} from "./shared/blocks/index.js";
import {
  EncounterStarted,
  MonsterCopySpawned,
  MonsterCopySpawningSystem,
  StartEncounter,
} from "./shared/encounter-commands.js";
import {
  AwardLoot,
  LootAwarded,
  LootAwardSystem,
  LootPlacedInScene,
  LootPlacementSystem,
  PlaceLootInScene,
} from "./shared/loot-commands.js";
import { invocationLinkKind } from "./shared/invocation-link-kind.js";
import { monsterLinkKind } from "./shared/monster-link-kind.js";
import { npcLinkKind } from "./shared/npc-link-kind.js";
import { spellLinkKind } from "./shared/spell-link-kind.js";
import { itemLinkKind } from "@vtt/items/shared";
import {
  AdvancementLogged,
  AdvancementLoggedTrait,
  AlliesEnemies,
  CharacterTraits,
  AcquireRelic,
  ApplyImmortalBurden,
  CirclesCheck,
  Conditions,
  CreateBlankInvocation,
  DeeperUnderstandingSpent,
  EditInvocationField,
  // Grind clock:
  DismissLightWentOut,
  Grind,
  GrindExtremeSet,
  GrindToll,
  GrindTollOpened,
  GrindTollRowApplied,
  GrindTurnSet,
  LightSourceWentOut,
  LightWentOutNotice,
  MarkGrindToll,
  NoticeDismissed,
  SetGrindExtreme,
  SetGrindTurn,
  // Light coverage:
  AssignLightCoverage,
  ClearLightCoverage,
  LightCoverage,
  LightCoverageChanged,
  // Items system:
  DropItem,
  EntryStateChanged,
  EquipItem,
  HealthCheck,
  Heroic,
  Identity,
  ImproveSkill,
  InvocationCatalogIndex,
  InvocationCreated,
  InvocationDerivedFrom,
  InvocationFieldEdited,
  InvocationForked,
  InvocationIdentity,
  InvocationPerformConsumeLogged,
  InvocationPerformConsumed,
  InvocationPerformInitiated,
  InvocationPerformRollable,
  InvocationRemoved,
  ItemDropped,
  ItemEquipped,
  ItemMoved,
  ItemPickedUp,
  ItemPlacedOnGround,
  ItemPosition,
  ItemRemovedFromGround,
  ItemUnequipped,
  LearnSkill,
  LevelBenefits,
  LoseRelic,
  LogAdvancement,
  LogSynergyAdvancement,
  LuckSpent,
  MoveItem,
  NatureCheck,
  OfCourseSpent,
  OpenSkillImprovement,
  OpenSkillLearning,
  PickUpItem,
  PinnedRolls,
  PinnedRollToggled,
  PlaceOnGround,
  Pools,
  RemoveFromGround,
  RawAbilities,
  RelicAcquired,
  RelicLost,
  Relics,
  ResourcesCheck,
  RollSpends,
  SetEntryState,
  SkillCheck,
  SpellCastRollable,
  SkillImproved,
  SkillImprovementOpened,
  SkillImprovementOpportunity,
  AbilityImproved,
  AbilityImprovementOpened,
  AbilityImprovementOpportunity,
  AbilityImprovedSystem,
  AbilityImprovementOpenedSystem,
  ImproveAbility,
  SkillLearned,
  SkillLearningOpened,
  SkillLearningOpportunity,
  Skills,
  SpendDeeperUnderstanding,
  SpendLuck,
  SpendOfCourse,
  SynergyAdvancementLoggedEvent,
  SynergyAdvancementLoggedTrait,
  TbArmor,
  TbCarries,
  TbContainer,
  TbItemSlotOptions,
  TbItemSpecialRules,
  TbLiquidVessel,
  TbRollModifierProvidersSlot,
  TbSkillBonuses,
  TbSupply,
  TbWeapon,
  TogglePinnedRoll,
  TownAbilities,
  TraitUsageLogged,
  TraitUsageLoggedTrait,
  LogTraitUsage,
  UnequipItem,
  UseTraitOnRoll,
  WhatYouFightFor,
  WhoYouAreNotes,
  WillCheck,
  Wises,
  // Monsters:
  CreateBlankMonster,
  CreateMonsterFromCatalog,
  MonsterCatalogIndex,
  MonsterCopy,
  MonsterCreated,
  MonsterRemoved,
  MonsterTemplate,
  RemoveMonster,
  TbConflictResource,
  TbMonster,
  TbMonsterDerivedFrom,
  TbMonsterSpecialRules,
  TbMonsterWeapons,
  // NPCs:
  CreateBlankNpc,
  CreateNpcFromCatalog,
  NpcCatalogIndex,
  NpcCreated,
  NpcRemoved,
  NpcTemplate,
  RemoveNpc,
  TbNpc,
  TbNpcDerivedFrom,
  // Spells:
  AddSpellToBook,
  AddSpellToLibrary,
  BurnScroll,
  BurnSpellbookSpell,
  ClearMemoryPalace,
  ConsumePalaceSpell,
  CreateBlankSpell,
  EditSpellField,
  FillMemoryPalace,
  RemoveInvocation,
  RemoveSpell,
  ScribeSpellToScroll,
  LibraryLocationSet,
  MemoryPalaceCapacityChanged,
  MemoryPalaceCleared,
  MemoryPalaceFilled,
  MemoryPalaceSpellMarkedCast,
  RemoveSpellFromBook,
  RemoveSpellFromLibrary,
  ScrollConsumed,
  ScrollScribed,
  ScrollSpawned,
  SetSpecialtySkill,
  SpecialtySkillSet,
  SpellCreated,
  SpellFieldEdited,
  SpellRemoved,
  SetMemoryPalaceCapacity,
  SpellAddedToBook,
  SpellAddedToLibrary,
  SpellCastConsumed,
  SpellCastConsumeLogged,
  SpellCastInitiated,
  SpellCatalogIndex,
  SpellDerivedFrom,
  SpellForked,
  SpellIdentity,
  SpellRemovedFromBook,
  SpellRemovedFromLibrary,
  TbLibrary,
  TbMemoryPalace,
  TbScroll,
  TbSpellBook,
  TbSpellCasting,
  TbSpellHomebrewProse,
  TbSpellLearning,
  // Invocations:
  TbInvocationHomebrewProse,
  TbInvocationPerforming,
  TbInvocationRelicLink,
  TbInvocationRelics,
} from "./shared/index.js";
import {
  AdvancementLoggedSystem,
  ChannelNatureTaxSystem,
  DeeperUnderstandingSpentSystem,
  FreshCancellationSystem,
  LuckSpentSystem,
  OfCourseSpentSystem,
  PinnedRollToggledSystem,
  SkillImprovedSystem,
  SkillImprovementOpenedSystem,
  SkillLearnedSystem,
  SkillLearningOpenedSystem,
  SkillLearningSweepSystem,
  SkillOpportunitySweepSystem,
  SpecialtySkillSetSystem,
  SynergyAdvancementLoggedSystem,
  GrindExtremeToggleSystem,
  GrindTickSystem,
  GrindTollOpenedSystem,
  GrindTollRowAppliedSystem,
  LightWentOutSystem,
  LightCoverageAutoClearOnBurnoutSystem,
  LightCoverageAutoClearOnDouseSystem,
  LightCoverageSystem,
  MonsterRemovalSystem,
  MonsterSpawningSystem,
  NpcRemovalSystem,
  NpcSpawningSystem,
  NoticeDismissSystem,
  TbBundleJoinSystem,
  TbBundleSplitSystem,
  TbCarryRebindOnForkSystem,
  TbCommitSpendsSystem,
  TbEntryStateSystem,
  TbItemDropSystem,
  TbItemEquipSystem,
  TbItemMoveSystem,
  TbItemPickUpSystem,
  TbItemPlacedSystem,
  TbItemRemovedFromGroundSystem,
  TbItemUnequipSystem,
  TraitUsageLoggedSystem,
  TB_INVOCATION_SYSTEMS,
  TB_SPELL_SYSTEMS,
} from "./server/index.js";
import {
  GrindTrackerStatusItem,
  LightTrackerStatusItem,
  TbAbilitiesSkillsTabFill,
  TbActionsFill,
  TbAbilityImprovementFeed,
  TbArcaneTabFill,
  TbChatTimelineContributor,
  TbGrindTollContributor,
  TbLightWentOutContributor,
  TbIdentityFill,
  TbInventoryTabFill,
  TbInvocationsTabFill,
  TbAtelierEditor,
  TbRailAccessory,
  TbRollActionsFill,
  TB_ITEM_DETAIL_SECTIONS,
  TbRollAtelierFeed,
  TbRollPaletteActions,
  TbSkillLearningTimelineContributor,
  TbTraitsWisesTabFill,
  TbVitalsFill,
  TbWhatYouFightForTabFill,
  TbWhoYouAreTabFill,
} from "./client/index.js";
import {
  PendingRollEditorsSlot,
  ResolvedRollFeedSlot,
  RollAtelierRailSlot,
} from "@vtt/characters/shared";
import { RollActionsSlot } from "@vtt/resolution/shared";
import { ItemDetailSectionsSlot } from "@vtt/items/shared";
import {
  NotificationsSlot,
  PaletteActionsSlot,
  PaletteCommandsSlot,
  WorkbenchStatusSlot,
} from "@vtt/shell-workbench/shared";
import { TB_SPAWN_MONSTER_PALETTE_COMMANDS } from "./client/spawn-monster-palette.js";
import { TB_SPAWN_NPC_PALETTE_COMMANDS } from "./client/spawn-npc-palette.js";
import { tbSeed } from "./data/seed.js";
import {
  ALL_CONFLICT_COMMANDS,
  ALL_CONFLICT_EVENTS,
  ALL_CONFLICT_TRAITS,
} from "./conflict/shared/index.js";
import { ALL_CONFLICT_SYSTEMS } from "./conflict/server/index.js";

/**
 * Hide monster entities from the Characters tab — they live on their
 * own Monsters tab via `MonstersPageProvider`. The same trait powers
 * the monster sheet's existence check.
 */
const tbMonsterListExclusion: CharacterListExclusion = {
  id: qualifiedName(
    "@vtt/system-torchbearer/exclude-monsters-from-characters-list",
  ) as CharacterListExclusion["id"],
  matchTrait: TbMonster,
};

/**
 * Hide NPC entities from the Characters tab — they live on their own
 * NPCs tab via `NpcsPageProvider`. The same trait powers the NPC
 * sheet's existence check.
 */
const tbNpcListExclusion: CharacterListExclusion = {
  id: qualifiedName(
    "@vtt/system-torchbearer/exclude-npcs-from-characters-list",
  ) as CharacterListExclusion["id"],
  matchTrait: TbNpc,
};

/**
 * Torchbearer 2nd Edition game system. Shape-only first pass:
 *   - All character-sheet traits modeled with full Zod schemas.
 *   - Skill catalog covers all three player-facing books
 *     (Dungeoneer's Handbook 33 + Lore Master's Manual 8 = 41 skills;
 *     Scholar's Guide adds NPC profession blocks but no new player
 *     skills).
 *   - Five top-level tabs in printed-sheet order, plus an Arcane tab
 *     that mounts unconditionally for now (class-conditional tab
 *     visibility lands when the slot system supports a `visible`
 *     predicate or a class-class registry).
 *   - Rollables compute notation only; modifiers from conditions /
 *     traits / wises / help / fate / persona / advantage all land
 *     with the next pass.
 *
 * Citations in code comments use printed page numbers (DH/LMM/SG)
 * per the rules-lookup skill convention. PDF page indices are not
 * stable across re-exports.
 */
export const systemTorchbearer = definePlugin({
  name: "@vtt/system-torchbearer",
  version: "0.1.0",
  dependsOn: [
    "@vtt/substrate@^0",
    "@vtt/books@^0",
    "@vtt/characters@^0",
    "@vtt/comms@^0",
    "@vtt/dice-tray@^0",
    "@vtt/items@^0",
    "@vtt/items-pages@^0",
    "@vtt/pdf-book@^0",
    "@vtt/scene@^0",
    "@vtt/resolution@^0",
    "@vtt/shell-workbench@^0",
    // The conflict Reference Board page provider lives in a sibling
    // plugin (mirrors @vtt/items-pages) so the core trait/event/
    // command/system surface stays loadable without shell-workbench
    // in unit tests. Listed here so the per-world plugin resolver
    // walks it transitively when this game system is chosen.
    "@vtt/system-torchbearer-pages@^0",
  ],
  gameSystem: true,
  traits: [
    Identity,
    WhatYouFightFor,
    Pools,
    Conditions,
    RawAbilities,
    TownAbilities,
    Skills,
    PinnedRolls,
    CharacterTraits,
    Wises,
    Relics,
    LevelBenefits,
    // Arcane (spells, books, scrolls, palace, library):
    SpellIdentity,
    TbSpellCasting,
    TbSpellLearning,
    TbSpellHomebrewProse,
    SpellDerivedFrom,
    SpellCatalogIndex,
    TbLibrary,
    TbMemoryPalace,
    TbSpellBook,
    TbScroll,
    SpellCastConsumed,
    // Invocations (per-character + catalog):
    InvocationIdentity,
    TbInvocationPerforming,
    TbInvocationHomebrewProse,
    InvocationDerivedFrom,
    InvocationCatalogIndex,
    TbInvocationRelics,
    TbInvocationRelicLink,
    InvocationPerformConsumed,
    AlliesEnemies,
    WhoYouAreNotes,
    Heroic,
    SkillImprovementOpportunity,
    AbilityImprovementOpportunity,
    SkillLearningOpportunity,
    AdvancementLoggedTrait,
    TraitUsageLoggedTrait,
    RollSpends,
    SynergyAdvancementLoggedTrait,
    // Items system (TB-specific layer):
    TbItemSlotOptions,
    TbWeapon,
    TbArmor,
    TbSupply,
    TbContainer,
    TbLiquidVessel,
    TbSkillBonuses,
    TbItemSpecialRules,
    TbCarries,
    ItemPosition,
    Grind,
    LightCoverage,
    LightWentOutNotice,
    GrindToll,
    // Monsters:
    TbMonster,
    TbMonsterWeapons,
    TbMonsterSpecialRules,
    TbMonsterDerivedFrom,
    MonsterTemplate,
    MonsterCopy,
    MonsterCatalogIndex,
    TbConflictResource,
    // NPCs:
    TbNpc,
    TbNpcDerivedFrom,
    NpcTemplate,
    NpcCatalogIndex,
    ...ALL_CONFLICT_TRAITS,
  ],
  events: [
    AdvancementLogged,
    DeeperUnderstandingSpent,
    LuckSpent,
    OfCourseSpent,
    PinnedRollToggled,
    SkillImproved,
    SkillImprovementOpened,
    AbilityImproved,
    AbilityImprovementOpened,
    SkillLearned,
    SkillLearningOpened,
    SpecialtySkillSet,
    SynergyAdvancementLoggedEvent,
    TraitUsageLogged,
    // Items system:
    ItemEquipped,
    ItemMoved,
    EntryStateChanged,
    ItemDropped,
    ItemPickedUp,
    ItemPlacedOnGround,
    ItemRemovedFromGround,
    ItemUnequipped,
    GrindTurnSet,
    GrindExtremeSet,
    LightSourceWentOut,
    NoticeDismissed,
    GrindTollOpened,
    GrindTollRowApplied,
    LightCoverageChanged,
    // Monsters:
    MonsterCreated,
    MonsterRemoved,
    MonsterCopySpawned,
    // NPCs:
    NpcCreated,
    NpcRemoved,
    // Encounters:
    EncounterStarted,
    LootAwarded,
    LootPlacedInScene,
    // Arcane:
    SpellAddedToLibrary,
    SpellRemovedFromLibrary,
    LibraryLocationSet,
    SpellAddedToBook,
    SpellRemovedFromBook,
    ScrollSpawned,
    ScrollConsumed,
    MemoryPalaceFilled,
    MemoryPalaceCleared,
    MemoryPalaceCapacityChanged,
    MemoryPalaceSpellMarkedCast,
    SpellCastInitiated,
    SpellCastConsumeLogged,
    SpellForked,
    ScrollScribed,
    SpellCreated,
    SpellRemoved,
    SpellFieldEdited,
    // Invocations:
    RelicAcquired,
    RelicLost,
    InvocationPerformInitiated,
    InvocationPerformConsumeLogged,
    InvocationCreated,
    InvocationRemoved,
    InvocationFieldEdited,
    InvocationForked,
    ...ALL_CONFLICT_EVENTS,
  ],
  commands: [
    ImproveSkill,
    ImproveAbility,
    LearnSkill,
    LogAdvancement,
    LogSynergyAdvancement,
    LogTraitUsage,
    OpenSkillImprovement,
    OpenSkillLearning,
    SetSpecialtySkill,
    SpendDeeperUnderstanding,
    SpendLuck,
    SpendOfCourse,
    TogglePinnedRoll,
    UseTraitOnRoll,
    // Items system:
    EquipItem,
    MoveItem,
    SetEntryState,
    DropItem,
    PickUpItem,
    PlaceOnGround,
    RemoveFromGround,
    UnequipItem,
    SetGrindTurn,
    SetGrindExtreme,
    DismissLightWentOut,
    MarkGrindToll,
    AssignLightCoverage,
    ClearLightCoverage,
    // Monsters:
    CreateBlankMonster,
    CreateMonsterFromCatalog,
    RemoveMonster,
    // NPCs:
    CreateBlankNpc,
    CreateNpcFromCatalog,
    RemoveNpc,
    // Encounters:
    StartEncounter,
    AwardLoot,
    PlaceLootInScene,
    // Arcane:
    AddSpellToLibrary,
    RemoveSpellFromLibrary,
    AddSpellToBook,
    RemoveSpellFromBook,
    FillMemoryPalace,
    ClearMemoryPalace,
    SetMemoryPalaceCapacity,
    ScribeSpellToScroll,
    ConsumePalaceSpell,
    BurnSpellbookSpell,
    BurnScroll,
    CreateBlankSpell,
    RemoveSpell,
    EditSpellField,
    // Invocations:
    AcquireRelic,
    LoseRelic,
    ApplyImmortalBurden,
    CreateBlankInvocation,
    RemoveInvocation,
    EditInvocationField,
    ...ALL_CONFLICT_COMMANDS,
  ],
  slots: [TbRollModifierProvidersSlot],
  systems: [
    AdvancementLoggedSystem,
    ChannelNatureTaxSystem,
    DeeperUnderstandingSpentSystem,
    FreshCancellationSystem,
    LuckSpentSystem,
    OfCourseSpentSystem,
    PinnedRollToggledSystem,
    SkillImprovedSystem,
    SkillImprovementOpenedSystem,
    AbilityImprovedSystem,
    AbilityImprovementOpenedSystem,
    SkillLearnedSystem,
    SkillLearningOpenedSystem,
    SkillLearningSweepSystem,
    SkillOpportunitySweepSystem,
    SpecialtySkillSetSystem,
    SynergyAdvancementLoggedSystem,
    TbCommitSpendsSystem,
    TraitUsageLoggedSystem,
    // Items system:
    TbItemEquipSystem,
    TbItemMoveSystem,
    TbEntryStateSystem,
    TbItemDropSystem,
    TbItemPickUpSystem,
    TbItemPlacedSystem,
    TbItemRemovedFromGroundSystem,
    TbItemUnequipSystem,
    TbBundleSplitSystem,
    TbBundleJoinSystem,
    TbCarryRebindOnForkSystem,
    // Grind clock + light decrement:
    GrindTickSystem,
    GrindExtremeToggleSystem,
    LightWentOutSystem,
    NoticeDismissSystem,
    GrindTollOpenedSystem,
    GrindTollRowAppliedSystem,
    // Light coverage:
    LightCoverageSystem,
    LightCoverageAutoClearOnDouseSystem,
    LightCoverageAutoClearOnBurnoutSystem,
    // Monsters:
    MonsterSpawningSystem,
    MonsterRemovalSystem,
    MonsterCopySpawningSystem,
    LootAwardSystem,
    LootPlacementSystem,
    // NPCs:
    NpcSpawningSystem,
    NpcRemovalSystem,
    ...TB_SPELL_SYSTEMS,
    ...TB_INVOCATION_SYSTEMS,
    ...ALL_CONFLICT_SYSTEMS,
  ],
  rollables: [
    WillCheck,
    HealthCheck,
    NatureCheck,
    ResourcesCheck,
    CirclesCheck,
    SkillCheck,
    SpellCastRollable,
    InvocationPerformRollable,
  ],
  fills: {
    [WorkbenchStatusSlot.name]: [GrindTrackerStatusItem, LightTrackerStatusItem],
    [CharacterSheetIdentitySlot.name]: [TbIdentityFill],
    [CharacterSheetVitalsSlot.name]: [TbVitalsFill],
    [CharacterSheetTabsSlot.name]: [
      TbWhoYouAreTabFill,
      TbWhatYouFightForTabFill,
      TbAbilitiesSkillsTabFill,
      TbTraitsWisesTabFill,
      TbInventoryTabFill,
      TbArcaneTabFill,
      TbInvocationsTabFill,
    ],
    [CharacterSheetActionsSlot.name]: [TbActionsFill],
    // Table-event cards (advancement / learning / grind toll / light
    // burnout) surface in the floating notifications overlay now, not
    // chat — so they're visible without opening the chat tab. Chat is
    // left for player text only.
    [NotificationsSlot.name]: [
      TbChatTimelineContributor,
      TbAbilityImprovementFeed,
      TbSkillLearningTimelineContributor,
      TbLightWentOutContributor,
      TbGrindTollContributor,
    ],
    [PendingRollEditorsSlot.name]: [TbAtelierEditor],
    [RollAtelierRailSlot.name]: [TbRailAccessory],
    [ResolvedRollFeedSlot.name]: [TbRollAtelierFeed],
    [RollActionsSlot.name]: [TbRollActionsFill],
    [ItemDetailSectionsSlot.name]: [...TB_ITEM_DETAIL_SECTIONS],
    [CharacterListExclusionSlot.name]: [
      tbMonsterListExclusion,
      tbNpcListExclusion,
    ],
    [LinkKindsSlot.name]: [
      monsterLinkKind,
      npcLinkKind,
      itemLinkKind,
      spellLinkKind,
      invocationLinkKind,
    ],
    [PaletteCommandsSlot.name]: [
      ...TB_SPAWN_MONSTER_PALETTE_COMMANDS,
      ...TB_SPAWN_NPC_PALETTE_COMMANDS,
    ],
    [PaletteActionsSlot.name]: [TbRollPaletteActions],
    [BlockKindsSlot.name]: [
      itemBlockKind as never,
      characterBlockKind as never,
      npcBlockKind as never,
      monsterBlockKind as never,
      encounterBlockKind as never,
      lootBlockKind as never,
    ],
  },
  seed: tbSeed,
});

export default systemTorchbearer;
