// mvtt, an RPG virtual tabletop
// Copyright (C) 2026, Adam Jacob
//
// This file is part of mvtt.
//
// mvtt is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation.
//
// mvtt is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with mvtt.  If not, see <https://www.gnu.org/licenses/>.

import { definePlugin } from "@vtt/substrate";
import {
  CharacterSheetActionsSlot,
  CharacterSheetIdentitySlot,
  CharacterSheetTabsSlot,
  CharacterSheetVitalsSlot,
} from "@vtt/characters/shared";
import {
  AdvancementLogged,
  AdvancementLoggedTrait,
  AlliesEnemies,
  CharacterTraits,
  CirclesCheck,
  Conditions,
  DeeperUnderstandingSpent,
  // Grind clock:
  DismissLightWentOut,
  Grind,
  GrindExtremeSet,
  GrindToll,
  GrindTollOpened,
  GrindTollRowApplied,
  GrindTurnSet,
  LightSourceWentOut,
  LightWentOutNotice,
  MarkGrindToll,
  NoticeDismissed,
  SetGrindExtreme,
  SetGrindTurn,
  // Items system:
  DropItem,
  EntryStateChanged,
  EquipItem,
  HealthCheck,
  Heroic,
  Identity,
  ImproveSkill,
  ItemDropped,
  ItemEquipped,
  ItemMoved,
  ItemPickedUp,
  ItemPlacedOnGround,
  ItemPosition,
  ItemRemovedFromGround,
  ItemUnequipped,
  LearnSkill,
  LogAdvancement,
  LogSynergyAdvancement,
  LuckSpent,
  MoveItem,
  NatureCheck,
  OfCourseSpent,
  OpenSkillImprovement,
  OpenSkillLearning,
  PickUpItem,
  PlaceOnGround,
  Pools,
  RemoveFromGround,
  RawAbilities,
  Relics,
  ResourcesCheck,
  RollSpends,
  SetEntryState,
  SkillCheck,
  SkillImproved,
  SkillImprovementOpened,
  SkillImprovementOpportunity,
  SkillLearned,
  SkillLearningOpened,
  SkillLearningOpportunity,
  Skills,
  Spells,
  SpendDeeperUnderstanding,
  SpendLuck,
  SpendOfCourse,
  SynergyAdvancementLoggedEvent,
  SynergyAdvancementLoggedTrait,
  TbArmor,
  TbCarries,
  TbContainer,
  TbItemSlotOptions,
  TbItemSpecialRules,
  TbRollModifierProvidersSlot,
  TbSkillBonuses,
  TbSupply,
  TbWeapon,
  TownAbilities,
  TraitUsageLogged,
  TraitUsageLoggedTrait,
  LogTraitUsage,
  UnequipItem,
  UseTraitOnRoll,
  WhatYouFightFor,
  WillCheck,
  Wises,
} from "./shared/index.js";
import {
  AdvancementLoggedSystem,
  ChannelNatureTaxSystem,
  DeeperUnderstandingSpentSystem,
  FreshCancellationSystem,
  LuckSpentSystem,
  OfCourseSpentSystem,
  SkillImprovedSystem,
  SkillImprovementOpenedSystem,
  SkillLearnedSystem,
  SkillLearningOpenedSystem,
  SkillLearningSweepSystem,
  SkillOpportunitySweepSystem,
  SynergyAdvancementLoggedSystem,
  GrindExtremeToggleSystem,
  GrindTickSystem,
  GrindTollOpenedSystem,
  GrindTollRowAppliedSystem,
  LightWentOutSystem,
  NoticeDismissSystem,
  TbBundleJoinSystem,
  TbBundleSplitSystem,
  TbCommitSpendsSystem,
  TbEntryStateSystem,
  TbItemDropSystem,
  TbItemEquipSystem,
  TbItemMoveSystem,
  TbItemPickUpSystem,
  TbItemPlacedSystem,
  TbItemRemovedFromGroundSystem,
  TbItemUnequipSystem,
  TraitUsageLoggedSystem,
} from "./server/index.js";
import {
  GrindTrackerView,
  TbAbilitiesSkillsTabFill,
  TbActionsFill,
  TbArcaneTabFill,
  TbChatTimelineContributor,
  TbGrindTollContributor,
  TbLightWentOutContributor,
  TbIdentityFill,
  TbInventoryTabFill,
  TbPendingRollContributor,
  TbRollActionsFill,
  TB_ITEM_DETAIL_SECTIONS,
  TbRollChatTimelineContributor,
  TbSkillLearningTimelineContributor,
  TbTraitsWisesTabFill,
  TbVitalsFill,
  TbWhatYouFightForTabFill,
  TbWhoYouAreTabFill,
} from "./client/index.js";
import { ChatTimelineContributorSlot } from "@vtt/comms/shared";
import { PendingRollContributorsSlot } from "@vtt/characters/shared";
import { RollActionsSlot } from "@vtt/resolution/shared";
import { ItemDetailSectionsSlot } from "@vtt/items/shared";
import { tbItemsSeed } from "./data/seed.js";

/**
 * Torchbearer 2nd Edition game system. Shape-only first pass:
 *   - All character-sheet traits modeled with full Zod schemas.
 *   - Skill catalog covers all three player-facing books
 *     (Dungeoneer's Handbook 33 + Lore Master's Manual 8 = 41 skills;
 *     Scholar's Guide adds NPC profession blocks but no new player
 *     skills).
 *   - Five top-level tabs in printed-sheet order, plus an Arcane tab
 *     that mounts unconditionally for now (class-conditional tab
 *     visibility lands when the slot system supports a `visible`
 *     predicate or a class-class registry).
 *   - Rollables compute notation only; modifiers from conditions /
 *     traits / wises / help / fate / persona / advantage all land
 *     with the next pass.
 *
 * Citations in code comments use printed page numbers (DH/LMM/SG)
 * per the rules-lookup skill convention. PDF page indices are not
 * stable across re-exports.
 */
export const systemTorchbearer = definePlugin({
  name: "@vtt/system-torchbearer",
  version: "0.1.0",
  dependsOn: [
    "@vtt/substrate@^0",
    "@vtt/books@^0",
    "@vtt/characters@^0",
    "@vtt/comms@^0",
    "@vtt/dice-tray@^0",
    "@vtt/items@^0",
    "@vtt/items-pages@^0",
    "@vtt/pdf-book@^0",
    "@vtt/scene@^0",
    "@vtt/resolution@^0",
    "@vtt/shell-workbench@^0",
  ],
  gameSystem: true,
  traits: [
    Identity,
    WhatYouFightFor,
    Pools,
    Conditions,
    RawAbilities,
    TownAbilities,
    Skills,
    CharacterTraits,
    Wises,
    Spells,
    Relics,
    AlliesEnemies,
    Heroic,
    SkillImprovementOpportunity,
    SkillLearningOpportunity,
    AdvancementLoggedTrait,
    TraitUsageLoggedTrait,
    RollSpends,
    SynergyAdvancementLoggedTrait,
    // Items system (TB-specific layer):
    TbItemSlotOptions,
    TbWeapon,
    TbArmor,
    TbSupply,
    TbContainer,
    TbSkillBonuses,
    TbItemSpecialRules,
    TbCarries,
    ItemPosition,
    Grind,
    LightWentOutNotice,
    GrindToll,
  ],
  events: [
    AdvancementLogged,
    DeeperUnderstandingSpent,
    LuckSpent,
    OfCourseSpent,
    SkillImproved,
    SkillImprovementOpened,
    SkillLearned,
    SkillLearningOpened,
    SynergyAdvancementLoggedEvent,
    TraitUsageLogged,
    // Items system:
    ItemEquipped,
    ItemMoved,
    EntryStateChanged,
    ItemDropped,
    ItemPickedUp,
    ItemPlacedOnGround,
    ItemRemovedFromGround,
    ItemUnequipped,
    GrindTurnSet,
    GrindExtremeSet,
    LightSourceWentOut,
    NoticeDismissed,
    GrindTollOpened,
    GrindTollRowApplied,
  ],
  commands: [
    ImproveSkill,
    LearnSkill,
    LogAdvancement,
    LogSynergyAdvancement,
    LogTraitUsage,
    OpenSkillImprovement,
    OpenSkillLearning,
    SpendDeeperUnderstanding,
    SpendLuck,
    SpendOfCourse,
    UseTraitOnRoll,
    // Items system:
    EquipItem,
    MoveItem,
    SetEntryState,
    DropItem,
    PickUpItem,
    PlaceOnGround,
    RemoveFromGround,
    UnequipItem,
    SetGrindTurn,
    SetGrindExtreme,
    DismissLightWentOut,
    MarkGrindToll,
  ],
  slots: [TbRollModifierProvidersSlot],
  systems: [
    AdvancementLoggedSystem,
    ChannelNatureTaxSystem,
    DeeperUnderstandingSpentSystem,
    FreshCancellationSystem,
    LuckSpentSystem,
    OfCourseSpentSystem,
    SkillImprovedSystem,
    SkillImprovementOpenedSystem,
    SkillLearnedSystem,
    SkillLearningOpenedSystem,
    SkillLearningSweepSystem,
    SkillOpportunitySweepSystem,
    SynergyAdvancementLoggedSystem,
    TbCommitSpendsSystem,
    TraitUsageLoggedSystem,
    // Items system:
    TbItemEquipSystem,
    TbItemMoveSystem,
    TbEntryStateSystem,
    TbItemDropSystem,
    TbItemPickUpSystem,
    TbItemPlacedSystem,
    TbItemRemovedFromGroundSystem,
    TbItemUnequipSystem,
    TbBundleSplitSystem,
    TbBundleJoinSystem,
    // Grind clock + light decrement:
    GrindTickSystem,
    GrindExtremeToggleSystem,
    LightWentOutSystem,
    NoticeDismissSystem,
    GrindTollOpenedSystem,
    GrindTollRowAppliedSystem,
  ],
  rollables: [
    WillCheck,
    HealthCheck,
    NatureCheck,
    ResourcesCheck,
    CirclesCheck,
    SkillCheck,
  ],
  views: [GrindTrackerView],
  fills: {
    [CharacterSheetIdentitySlot.name]: [TbIdentityFill],
    [CharacterSheetVitalsSlot.name]: [TbVitalsFill],
    [CharacterSheetTabsSlot.name]: [
      TbWhoYouAreTabFill,
      TbWhatYouFightForTabFill,
      TbAbilitiesSkillsTabFill,
      TbTraitsWisesTabFill,
      TbArcaneTabFill,
      TbInventoryTabFill,
    ],
    [CharacterSheetActionsSlot.name]: [TbActionsFill],
    [ChatTimelineContributorSlot.name]: [
      TbChatTimelineContributor,
      TbRollChatTimelineContributor,
      TbSkillLearningTimelineContributor,
      TbLightWentOutContributor,
      TbGrindTollContributor,
    ],
    [PendingRollContributorsSlot.name]: [TbPendingRollContributor],
    [RollActionsSlot.name]: [TbRollActionsFill],
    [ItemDetailSectionsSlot.name]: [...TB_ITEM_DETAIL_SECTIONS],
  },
  seed: tbItemsSeed,
});

export default systemTorchbearer;
